spring:
  application:
    name: appengine-spring-boot
  threads:
    virtual:
      enabled: true
  main:
    banner-mode: "off"
  jackson:
    serialization:
      indent_output: true
  mvc:
    view:
      prefix: /WEB-INF/jsp/
      suffix: .jsp
  cache:
    type: jcache

server:
  port: 8080
  servlet:
    context-path: /
    session:
      cookie:
        http-only: true
        secure: true
  error:
    whitelabel:
      enabled: false

logging:
  level:
    root: INFO
    com.github.michaeltecourt: DEBUG
    org.springframework.web: INFO

management:
  health:
    diskspace:
      threshold: 0
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    health:
      show-details: ALWAYS
